# Generated by Django 5.2.12 on 2026-03-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Quizzes'},
        ),
    ]
