# Generated by Django 5.2.12 on 2026-03-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_repeatable',
        ),
    ]
