# Generated by Django 5.2.12 on 2026-03-09 04:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_allow_late_submissions_quiz_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='QuizItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('identification', 'Identification'), ('single_choice', 'Multiple Choice'), ('multiple_answer', 'Multiple Answer'), ('true_false', 'True/False'), ('matching', 'Matching'), ('ordering', 'Ordering')], max_length=20)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(blank=True, default='', max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('tf_correct', models.BooleanField(default=True)),
                ('points', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('sort_order', models.IntegerField(default=0)),
                ('media', models.ImageField(blank=True, null=True, upload_to='quiz_items/')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quizzes.quiz')),
            ],
            options={
                'db_table': 'quiz_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
