# Generated by Django 5.2.12 on 2026-03-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quiz_time_limit_minutes_quizitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='completed_at',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
