# Generated by Django 5.2.12 on 2026-03-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_rename_completed_at_quizattempt_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='can_backtrack',
            field=models.BooleanField(default=True, help_text='Allow students to navigate back and forth between questions?'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_answers_at_end',
            field=models.BooleanField(default=True, help_text='Display correct answers to students after they complete the quiz?'),
        ),
    ]
