# Generated by Django 5.2.12 on 2026-03-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quiz_can_backtrack_quiz_show_answers_at_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='attempts_allowed',
            field=models.IntegerField(blank=True, default=1, help_text='Leave blank or set to 0 for unlimited attempts.', null=True),
        ),
    ]
