# Generated by Django 6.0.3 on 2026-03-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_quizattempt_time_taken_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='late_penalty_percentage',
            field=models.FloatField(default=0.0, help_text='Percentage to deduct if submitted late (0-100).'),
        ),
    ]
