# Generated by Django 6.0.3 on 2026-03-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_quiz_is_active_quiz_late_penalty_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.CharField(blank=True, help_text='For AI generated quizzes', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='specialization',
            field=models.CharField(blank=True, help_text='For AI generated quizzes', max_length=100, null=True),
        ),
    ]
