# Generated by Django 6.0.3 on 2026-03-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_quiz_category_quiz_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizitem',
            name='bloom_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('draft', 'Draft'), ('published', 'Published'), ('error', 'Error')], default='draft', max_length=10),
        ),
    ]
