# Generated by Django 6.0.3 on 2026-03-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_quizitem_bloom_level_alter_quiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='meta',
            field=models.JSONField(blank=True, default=dict, help_text='Stores metadata about AI generation like source files, etc.'),
        ),
    ]
