# Generated by Django 6.0.3 on 2026-04-04 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_quiz_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['author', 'status'], name='quizzes_author__b39700_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['status', 'availability'], name='quizzes_status_cda201_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['-updated_at'], name='quizzes_updated_70eb13_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'user', 'end_time'], name='quiz_attemp_quiz_id_1f76a1_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', '-start_time'], name='quiz_attemp_user_id_22a6a2_idx'),
        ),
        migrations.AddIndex(
            model_name='quizitem',
            index=models.Index(fields=['quiz', 'sort_order'], name='quiz_items_quiz_id_bf4ee1_idx'),
        ),
    ]
