# Generated by Django 6.0.3 on 2026-04-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_quiz_quizzes_author__b39700_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='reference_file_1',
            field=models.FileField(blank=True, null=True, upload_to='quiz_references/'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='reference_file_2',
            field=models.FileField(blank=True, null=True, upload_to='quiz_references/'),
        ),
    ]
