# Generated by Django 5.2.12 on 2026-03-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('quiz_share', 'Quiz Share'), ('system_alert', 'System Alert'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
