# Generated by Django 6.0.3 on 2026-03-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_notification_options_remove_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Accepted'), ('quiz_share', 'Quiz Share'), ('system_alert', 'System Alert'), ('general', 'General'), ('quiz_deadline', 'Quiz Deadline')], default='general', max_length=50),
        ),
    ]
